substitutions:
  devicename: "ceiling-light"
  friendly_name: "Ceiling Light"

esphome:
  platform: ESP8266
  board: esp12e

  name: ${devicename}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True

  comment: Dimmable ceiling light with CCT and motion detector.
  project:
    name: Marvin's.${friendly_name}
    version: "1.0.2"

  on_boot:
    - script.execute: offline_light

dashboard_import:
  package_import_url: github://11marvin/esp8266-lvl-light/Firmware/esp8266-ceiling-light.yaml@master

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {} # This spawns an AP with the device name and mac address with no password.

web_server:
  port: 80
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable Home Assistant OTA
ota:
  platform: esphome


script:
  - id: offline_light
    mode: restart     # Light will be kept on during 10 minutes since
                      # the latest time the script is executed
    then:
      - light.turn_on:
          id: mylight 
          brightness: 90%
          color_temperature: 3900K
      - delay: 10 min
      - light.turn_off: mylight

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: motion
    pin:
      number: GPIO13
    name: motion
    device_class: motion
    on_press:
      - while:
          condition:
            binary_sensor.is_on: motion
          then:
            - if:
                condition:
                  not:
                    api.connected:
                then:
                  - script.execute: offline_light
            - delay: 1 min

switch:
  - platform: restart
    name: Restart
    
light:
  - platform: color_temperature
    id: mylight
    name: "Light"
    brightness: output_brightness
    color_temperature: output_temperature
    cold_white_color_temperature: 4600 K
    warm_white_color_temperature: 2800 K

  - platform: monochromatic
    name: "Notification LED"
    output: output_component1
    id: led

  - platform: monochromatic
    name: "Set light brightness output"
    entity_category: config
    output: output_brightness
    id: brightness

  - platform: monochromatic
    name: "Set light temperature output"
    entity_category: config
    output: output_temperature
    id: temperature
    
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO2
    inverted: True
    
  - platform: esp8266_pwm
    id: output_brightness
    min_power: 0.06
    zero_means_zero: True
    pin: GPIO12
    inverted: False
    
  - platform: esp8266_pwm
    id: output_temperature
    pin: GPIO14
    inverted: True
