substitutions:
  devicename: "ceiling-light"
  friendly_name: "Ceiling Light"

esphome:
  platform: ESP8266
  board: esp12e

  name: ${devicename}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True

  comment: Dimmable ceiling light with CCT and motion detector.
  project:
    name: Marvin's.${friendly_name}
    version: "1.0.0"
  on_boot:
    - light.turn_on:
        id: mylight 
        brightness: 90%
        color_temperature: 4700K

dashboard_import:
  package_import_url: github://11marvin/esp8266-lvl-light/Firmware/esp8266-ceiling-light.yaml@main

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {} # This spawns an AP with the device name and mac address with no password.

web_server:
  port: 80
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable Home Assistant OTA
ota:


script:
  - id: offline_light
    mode: restart     # Light will be kept on during 15 minutes since
                      # the latest time the script is executed
    then:
      - light.turn_on:
          id: mylight 
          brightness: 90%
          color_temperature: 3900K
      - delay: 10 min
      - light.turn_off: mylight

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: motion
    pin:
      number: GPIO13
      # mode: INPUT_PULLUP
      # inverted: True
    name: motion
    device_class: motion
    on_press:
      - while:
          condition:
            binary_sensor.is_on: motion
          then:
            - if:
                condition:
                  not:
                    api.connected:
                then:
                  - script.execute: offline_light
            - delay: 1 min

switch:
  - platform: restart
    name: Restart
    
light:
  - platform: color_temperature
    id: mylight
    name: None
    brightness: output_brightness
    color_temperature: output_temperature
    # cold_white_color_temperature: 6536 K
    cold_white_color_temperature: 5000 K
    warm_white_color_temperature: 2800 K
  - platform: monochromatic
    name: "LED"
    output: output_component1
    id: led
  - platform: monochromatic
    name: "brightness"
    output: output_brightness
    id: brightness
  - platform: monochromatic
    name: "temperature"
    output: output_temperature
    id: temperature
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO2
    inverted: True
  - platform: esp8266_pwm
    id: output_brightness
    min_power: 0.06
    zero_means_zero: True
    # frequency: 10000 Hz
    pin: GPIO12
    inverted: False
  - platform: esp8266_pwm
    id: output_temperature
    # frequency: 10000 Hz
    pin: GPIO14
    inverted: True
